namespace Emwin.Tests
{
    internal static class BulletinContent
    {
        public const string TornadoWarning = @"WFUS53 KDDC 050056
TORDDC
KSC101-135-050130-
/O.NEW.KDDC.TO.W.0045.150605T0056Z-150605T0130Z/

BULLETIN - EAS ACTIVATION REQUESTED
TORNADO WARNING
NATIONAL WEATHER SERVICE DODGE CITY KS
756 PM CDT THU JUN 4 2015

THE NATIONAL WEATHER SERVICE IN DODGE CITY HAS ISSUED A

* TORNADO WARNING FOR...
  NORTHWESTERN NESS COUNTY IN WEST CENTRAL KANSAS...
  NORTHEASTERN LANE COUNTY IN WEST CENTRAL KANSAS...

* UNTIL 830 PM CDT
    
* AT 755 PM CDT...A SEVERE THUNDERSTORM CAPABLE OF PRODUCING A
  TORNADO WAS LOCATED 3 MILES NORTH OF PENDENNIS...MOVING NORTHEAST
  AT 10 MPH.

  HAZARD...TORNADO.

  SOURCE...RADAR INDICATED ROTATION.

  IMPACT...FLYING DEBRIS WILL BE DANGEROUS TO THOSE CAUGHT WITHOUT
           SHELTER. MOBILE HOMES WILL BE DAMAGED OR DESTROYED.
           DAMAGE TO ROOFS...WINDOWS AND VEHICLES WILL OCCUR.TREE
           DAMAGE IS LIKELY. 

* THIS TORNADIC THUNDERSTORM WILL REMAIN OVER MAINLY RURAL AREAS OF
  NORTHWESTERN NESS AND NORTHEASTERN LANE COUNTIES.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

TAKE COVER NOW! MOVE TO A BASEMENT OR AN INTERIOR ROOM ON THE LOWEST
FLOOR OF A STURDY BUILDING. AVOID WINDOWS. IF IN A MOBILE HOME...A
VEHICLE OR OUTDOORS...MOVE TO THE CLOSEST SUBSTANTIAL SHELTER AND
PROTECT YOURSELF FROM FLYING DEBRIS.

&&

LAT...LON 3870 10017 3865 10017 3859 10038 3870 10045
TIME...MOT...LOC 0055Z 227DEG 17KT 3869 10033 

TORNADO...RADAR INDICATED
HAIL...<.75IN

$$

FINCH";

        public const string FloodWarning = @"
WGUS43 KOAX 070445
FLWOAX

BULLETIN - IMMEDIATE BROADCAST REQUESTED
FLOOD WARNING
NATIONAL WEATHER SERVICE OMAHA/VALLEY NEBRASKA
1145 PM CDT SAT JUN 6 2015

NEC021-039-167-070745-
/O.NEW.KOAX.FA.W.0009.150607T0445Z-150607T0745Z/
/00000.0.ER.000000T0000Z.000000T0000Z.000000T0000Z.OO/
STANTON NE-CUMING NE-BURT NE-
1145 PM CDT SAT JUN 6 2015

THE NATIONAL WEATHER SERVICE IN OMAHA HAS ISSUED A

* FLOOD WARNING FOR URBAN AREAS AND SMALL STREAMS IN...
  STANTON COUNTY IN NORTHEASTERN NEBRASKA...
  CUMING COUNTY IN NORTHEASTERN NEBRASKA...
  BURT COUNTY IN EAST CENTRAL NEBRASKA...

* UNTIL 245 AM CDT

* AT 1143 PM CDT...DOPPLER RADAR INDICATED THUNDERSTORMS PRODUCING 
  HEAVY RAIN WHICH WILL CAUSE FLOODING. RAINFALL RATES OF BETWEEN 1 
  TO 2 INCHES AN HOUR WERE INDICATED BY RADAR.

* SOME LOCATIONS THAT WILL EXPERIENCE FLOODING INCLUDE...
  WEST POINT...TEKAMAH...STANTON...WISNER...LYONS...BEEMER...
  BANCROFT...DECATUR...PILGER...CRAIG...OAKLAND...THE HIGHWAY 15 AND
  32 JUNCTION...8 MILES SOUTH OF STANTON...10 MILES WEST OF WEST
  POINT...THE HIGHWAY 9 AND 51 JUNCTION AND SUMMIT LAKE STATE
  RECREATION AREA.

ADDITIONAL RAINFALL AMOUNTS OF UP TO AN INCH ARE POSSIBLE IN THE 
WARNED AREA BEFORE STORMS MOVE OUT OF THE AREA.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

EXCESSIVE RUNOFF FROM HEAVY RAINFALL WILL CAUSE FLOODING OF SMALL
CREEKS AND STREAMS...AS WELL AS FARM AND COUNTRY ROADS. DO NOT
ATTEMPT TO TRAVEL ACROSS FLOODED ROADS. FIND ALTERNATE ROUTES.

&&

LAT...LON 4209 9736 4209 9656 4201 9656 4202 9623
      4200 9624 4201 9621 4175 9609 4174 9611
      4175 9736

$$

FOBERT";

    }
}
