//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emwin.Core.References {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GraphicProduct {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphicProduct() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emwin.Core.References.GraphicProduct", typeof(GraphicProduct).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic Path.
        /// </summary>
        public static string ATPATHUS {
            get {
                return ResourceManager.GetString("ATPATHUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land/Sea Temperatures and Clouds.
        /// </summary>
        public static string CMPWLDUS {
            get {
                return ResourceManager.GetString("CMPWLDUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 1 QPF &amp; 850 HPA Winds.
        /// </summary>
        public static string CRB1WBCA {
            get {
                return ResourceManager.GetString("CRB1WBCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 2 QPF &amp; 850 HPA Winds.
        /// </summary>
        public static string CRB2WBCA {
            get {
                return ResourceManager.GetString("CRB2WBCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 3 QPF &amp; 850 HPA Winds.
        /// </summary>
        public static string CRB3WBCA {
            get {
                return ResourceManager.GetString("CRB3WBCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribbean Surface Analysis.
        /// </summary>
        public static string CSA001US {
            get {
                return ResourceManager.GetString("CSA001US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba Radar.
        /// </summary>
        public static string CUBARADR {
            get {
                return ResourceManager.GetString("CUBARADR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Hour Flash Flood Guidance.
        /// </summary>
        public static string FFG001US {
            get {
                return ResourceManager.GetString("FFG001US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Hour Flash Flood Guidance.
        /// </summary>
        public static string FFG003US {
            get {
                return ResourceManager.GetString("FFG003US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Hour Flash Flood Guidance.
        /// </summary>
        public static string FFG006US {
            get {
                return ResourceManager.GetString("FFG006US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOES 8 Satellite Image - All United States.
        /// </summary>
        public static string G08CIRUS {
            get {
                return ResourceManager.GetString("G08CIRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOES 8 Satellite Image - Southern US / Caribbean.
        /// </summary>
        public static string G08HURUS {
            get {
                return ResourceManager.GetString("G08HURUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOES 10 Satellite Image - Western United States.
        /// </summary>
        public static string G10CIRUS {
            get {
                return ResourceManager.GetString("G10CIRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOES 10 Satellite Image - Pacific Ocean.
        /// </summary>
        public static string G10FDIUS {
            get {
                return ResourceManager.GetString("G10FDIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Image Earth View - Pacific Ocean.
        /// </summary>
        public static string GMS005US {
            get {
                return ResourceManager.GetString("GMS005US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant River Flood Outlook.
        /// </summary>
        public static string GPHJ88US {
            get {
                return ResourceManager.GetString("GPHJ88US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000Z Surface Analysis.
        /// </summary>
        public static string IMGFNT00 {
            get {
                return ResourceManager.GetString("IMGFNT00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0600Z Surface Analysis.
        /// </summary>
        public static string IMGFNT06 {
            get {
                return ResourceManager.GetString("IMGFNT06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200Z Surface Analysis.
        /// </summary>
        public static string IMGFNT12 {
            get {
                return ResourceManager.GetString("IMGFNT12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800Z Surface Analysis.
        /// </summary>
        public static string IMGFNT18 {
            get {
                return ResourceManager.GetString("IMGFNT18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Image - Caribbean Islands.
        /// </summary>
        public static string IMGSJUPR {
            get {
                return ResourceManager.GetString("IMGSJUPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOES Sounder.
        /// </summary>
        public static string IMGSNDUS {
            get {
                return ResourceManager.GetString("IMGSNDUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Image - Southwestern Pacific.
        /// </summary>
        public static string IMGSWPUS {
            get {
                return ResourceManager.GetString("IMGSWPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Warnings, Watches and Advisories.
        /// </summary>
        public static string IMGWWAUS {
            get {
                return ResourceManager.GetString("IMGWWAUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Image Earth View - Indian Ocean.
        /// </summary>
        public static string INDCIRUS {
            get {
                return ResourceManager.GetString("INDCIRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Image Earth View - Africa.
        /// </summary>
        public static string METFIREU {
            get {
                return ResourceManager.GetString("METFIREU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Hour QPF 91e.
        /// </summary>
        public static string MOD91EUS {
            get {
                return ResourceManager.GetString("MOD91EUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-Hour Forecast of Fronts/Pressure and Weather.
        /// </summary>
        public static string MOD92FBW {
            get {
                return ResourceManager.GetString("MOD92FBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Hour QPF 93e.
        /// </summary>
        public static string MOD93SUS {
            get {
                return ResourceManager.GetString("MOD93SUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive Rainfall Potential Outlook.
        /// </summary>
        public static string MOD94SUS {
            get {
                return ResourceManager.GetString("MOD94SUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36-Hour Forecast of Fronts/Pressure and Weather.
        /// </summary>
        public static string MOD96FBW {
            get {
                return ResourceManager.GetString("MOD96FBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 1 Convective Outlook.
        /// </summary>
        public static string MODDY1US {
            get {
                return ResourceManager.GetString("MODDY1US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 2 Convective Outlook.
        /// </summary>
        public static string MODDY2US {
            get {
                return ResourceManager.GetString("MODDY2US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-Hour Day 1 QPF 94q.
        /// </summary>
        public static string MODQP1US {
            get {
                return ResourceManager.GetString("MODQP1US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-Hour Day 2 QPF 98q.
        /// </summary>
        public static string MODQP2US {
            get {
                return ResourceManager.GetString("MODQP2US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaska.
        /// </summary>
        public static string RADALLAK {
            get {
                return ResourceManager.GetString("RADALLAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        public static string RADALLGU {
            get {
                return ResourceManager.GetString("RADALLGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawaii.
        /// </summary>
        public static string RADALLHI {
            get {
                return ResourceManager.GetString("RADALLHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        public static string RADALLPR {
            get {
                return ResourceManager.GetString("RADALLPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXRAD All US.
        /// </summary>
        public static string RADALLUS {
            get {
                return ResourceManager.GetString("RADALLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Great Lakes.
        /// </summary>
        public static string RADGRTLK {
            get {
                return ResourceManager.GetString("RADGRTLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northeast.
        /// </summary>
        public static string RADNTHES {
            get {
                return ResourceManager.GetString("RADNTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Northwest.
        /// </summary>
        public static string RADPACNW {
            get {
                return ResourceManager.GetString("RADPACNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Southwest.
        /// </summary>
        public static string RADPACSW {
            get {
                return ResourceManager.GetString("RADPACSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Rockies.
        /// </summary>
        public static string RADRCKNT {
            get {
                return ResourceManager.GetString("RADRCKNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Rockies.
        /// </summary>
        public static string RADRCKST {
            get {
                return ResourceManager.GetString("RADRCKST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXRAD Reflectivity.
        /// </summary>
        public static string RADREFUS {
            get {
                return ResourceManager.GetString("RADREFUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Mississippi Valley.
        /// </summary>
        public static string RADSMSVY {
            get {
                return ResourceManager.GetString("RADSMSVY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeast.
        /// </summary>
        public static string RADSTHES {
            get {
                return ResourceManager.GetString("RADSTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Plains.
        /// </summary>
        public static string RADSTHPL {
            get {
                return ResourceManager.GetString("RADSTHPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Mississippi Valley.
        /// </summary>
        public static string RADUMSVY {
            get {
                return ResourceManager.GetString("RADUMSVY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth View.
        /// </summary>
        public static string SESALLUS {
            get {
                return ResourceManager.GetString("SESALLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic Tropical Cyclones.
        /// </summary>
        public static string TRKATLUS {
            get {
                return ResourceManager.GetString("TRKATLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northeast Pacific Tropical Cyclones.
        /// </summary>
        public static string TRKNEPUS {
            get {
                return ResourceManager.GetString("TRKNEPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Indian Tropical Cyclones.
        /// </summary>
        public static string TRKNINUS {
            get {
                return ResourceManager.GetString("TRKNINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Pacific Tropical Cyclones.
        /// </summary>
        public static string TRKNWPUS {
            get {
                return ResourceManager.GetString("TRKNWPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeast Pacific Tropical Cyclones.
        /// </summary>
        public static string TRKSEPUS {
            get {
                return ResourceManager.GetString("TRKSEPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Indian Tropical Cyclones.
        /// </summary>
        public static string TRKSINUS {
            get {
                return ResourceManager.GetString("TRKSINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southwest Pacific Tropical Cyclones.
        /// </summary>
        public static string TRKSWPUS {
            get {
                return ResourceManager.GetString("TRKSWPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldwide Tropical Cyclones.
        /// </summary>
        public static string TRKWLDUS {
            get {
                return ResourceManager.GetString("TRKWLDUS", resourceCulture);
            }
        }
    }
}
