//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emwin.Core.References {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextProduct {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextProduct() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emwin.Core.References.TextProduct", typeof(TextProduct).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 Hour Report.
        /// </summary>
        public static string _18A {
            get {
                return ResourceManager.GetString("18A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hour Report.
        /// </summary>
        public static string _24A {
            get {
                return ResourceManager.GetString("24A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Weather Outlook.
        /// </summary>
        public static string _30L {
            get {
                return ResourceManager.GetString("30L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-hourly Space Weather Conditions and Forecast.
        /// </summary>
        public static string _3HR {
            get {
                return ResourceManager.GetString("3HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm/Alert Administrative Message.
        /// </summary>
        public static string ADA {
            get {
                return ResourceManager.GetString("ADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Administrative Message.
        /// </summary>
        public static string ADM {
            get {
                return ResourceManager.GetString("ADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Message.
        /// </summary>
        public static string ADR {
            get {
                return ResourceManager.GetString("ADR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Space Weather Advisory.
        /// </summary>
        public static string ADV {
            get {
                return ResourceManager.GetString("ADV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Message for NWWS.
        /// </summary>
        public static string ADW {
            get {
                return ResourceManager.GetString("ADW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Alert Non-Receipt.
        /// </summary>
        public static string ADX {
            get {
                return ResourceManager.GetString("ADX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Forecast Discussion.
        /// </summary>
        public static string AFD {
            get {
                return ResourceManager.GetString("AFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Forecast Matrices.
        /// </summary>
        public static string AFM {
            get {
                return ResourceManager.GetString("AFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Forecast Product.
        /// </summary>
        public static string AFP {
            get {
                return ResourceManager.GetString("AFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural Forecast.
        /// </summary>
        public static string AGF {
            get {
                return ResourceManager.GetString("AGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural Observations.
        /// </summary>
        public static string AGO {
            get {
                return ResourceManager.GetString("AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Force High Density Obs.
        /// </summary>
        public static string AHO {
            get {
                return ResourceManager.GetString("AHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Weather Message Alert.
        /// </summary>
        public static string ALT {
            get {
                return ResourceManager.GetString("ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Stagnation Guidance Narrative.
        /// </summary>
        public static string APG {
            get {
                return ResourceManager.GetString("APG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar Orbiter Images.
        /// </summary>
        public static string APT {
            get {
                return ResourceManager.GetString("APT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality Message.
        /// </summary>
        public static string AQA {
            get {
                return ResourceManager.GetString("AQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality Index Statement.
        /// </summary>
        public static string AQI {
            get {
                return ResourceManager.GetString("AQI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Stagnation Advisory.
        /// </summary>
        public static string ASA {
            get {
                return ResourceManager.GetString("ASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalanche Watch.
        /// </summary>
        public static string AVA {
            get {
                return ResourceManager.GetString("AVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Verification Matrix.
        /// </summary>
        public static string AVM {
            get {
                return ResourceManager.GetString("AVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalanche Warning.
        /// </summary>
        public static string AVW {
            get {
                return ResourceManager.GetString("AVW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Attack Warning.
        /// </summary>
        public static string AWG {
            get {
                return ResourceManager.GetString("AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Weather Summary.
        /// </summary>
        public static string AWS {
            get {
                return ResourceManager.GetString("AWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Weather Update.
        /// </summary>
        public static string AWU {
            get {
                return ResourceManager.GetString("AWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Weather Warning.
        /// </summary>
        public static string AWW {
            get {
                return ResourceManager.GetString("AWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buoy Reports.
        /// </summary>
        public static string BOY {
            get {
                return ResourceManager.GetString("BOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Abduction Emergency.
        /// </summary>
        public static string CAE {
            get {
                return ResourceManager.GetString("CAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded City Forecast.
        /// </summary>
        public static string CCF {
            get {
                return ResourceManager.GetString("CCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Danger Warning.
        /// </summary>
        public static string CDW {
            get {
                return ResourceManager.GetString("CDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Emergency Message.
        /// </summary>
        public static string CEM {
            get {
                return ResourceManager.GetString("CEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate F-6 products.
        /// </summary>
        public static string CF6 {
            get {
                return ResourceManager.GetString("CF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastal/Lakeshore Hazard Messages.
        /// </summary>
        public static string CFW {
            get {
                return ResourceManager.GetString("CFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coast Guard Surface Report.
        /// </summary>
        public static string CGR {
            get {
                return ResourceManager.GetString("CGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Hurricane Guidance.
        /// </summary>
        public static string CHG {
            get {
                return ResourceManager.GetString("CHG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Report Annual.
        /// </summary>
        public static string CLA {
            get {
                return ResourceManager.GetString("CLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Report Daily.
        /// </summary>
        public static string CLI {
            get {
                return ResourceManager.GetString("CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Report Monthly.
        /// </summary>
        public static string CLM {
            get {
                return ResourceManager.GetString("CLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Report Seasonal.
        /// </summary>
        public static string CLS {
            get {
                return ResourceManager.GetString("CLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded Climatological Monthly Means.
        /// </summary>
        public static string CMM {
            get {
                return ResourceManager.GetString("CMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded Analysis and Forecasts.
        /// </summary>
        public static string COD {
            get {
                return ResourceManager.GetString("COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded Port Forecast.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Selected Cities Forecast.
        /// </summary>
        public static string CSC {
            get {
                return ResourceManager.GetString("CSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Space Weather Indices.
        /// </summary>
        public static string CUR {
            get {
                return ResourceManager.GetString("CUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Weather Advisory.
        /// </summary>
        public static string CWA {
            get {
                return ResourceManager.GetString("CWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastal Waters Forecast.
        /// </summary>
        public static string CWF {
            get {
                return ResourceManager.GetString("CWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Weather Statement.
        /// </summary>
        public static string CWS {
            get {
                return ResourceManager.GetString("CWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Space Weather Summary and Forcast.
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drought Information.
        /// </summary>
        public static string DGT {
            get {
                return ResourceManager.GetString("DGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar Hourly Digital Precipitation.
        /// </summary>
        public static string DPA {
            get {
                return ResourceManager.GetString("DPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnumbered Depression.
        /// </summary>
        public static string DSA {
            get {
                return ResourceManager.GetString("DSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asos Daily Summary.
        /// </summary>
        public static string DSM {
            get {
                return ResourceManager.GetString("DSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 TO 5 Day Extended Forecast.
        /// </summary>
        public static string EFP {
            get {
                return ResourceManager.GetString("EFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average 6 TO 10 Day Weather Outlook.
        /// </summary>
        public static string EOL {
            get {
                return ResourceManager.GetString("EOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average 6 TO 10 Day Weather Outlook.
        /// </summary>
        public static string EON {
            get {
                return ResourceManager.GetString("EON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquake Information Bulletin.
        /// </summary>
        public static string EQI {
            get {
                return ResourceManager.GetString("EQI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquake Report.
        /// </summary>
        public static string EQR {
            get {
                return ResourceManager.GetString("EQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquake Warning.
        /// </summary>
        public static string EQW {
            get {
                return ResourceManager.GetString("EQW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Potential Outlook.
        /// </summary>
        public static string ESF {
            get {
                return ResourceManager.GetString("ESF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Streamflow Guidance.
        /// </summary>
        public static string ESG {
            get {
                return ResourceManager.GetString("ESG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Streamflow Prediction.
        /// </summary>
        public static string ESP {
            get {
                return ResourceManager.GetString("ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Supply Outlook.
        /// </summary>
        public static string ESS {
            get {
                return ResourceManager.GetString("ESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation Immediate.
        /// </summary>
        public static string EVI {
            get {
                return ResourceManager.GetString("EVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Wind Warning.
        /// </summary>
        public static string EWW {
            get {
                return ResourceManager.GetString("EWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (Pacific).
        /// </summary>
        public static string FA0 {
            get {
                return ResourceManager.GetString("FA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (Northeast U.S.).
        /// </summary>
        public static string FA1 {
            get {
                return ResourceManager.GetString("FA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (Southeast U.S.).
        /// </summary>
        public static string FA2 {
            get {
                return ResourceManager.GetString("FA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (North Cent U.S.).
        /// </summary>
        public static string FA3 {
            get {
                return ResourceManager.GetString("FA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (South Cent U.S.).
        /// </summary>
        public static string FA4 {
            get {
                return ResourceManager.GetString("FA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (U.S. Rocky Mts.).
        /// </summary>
        public static string FA5 {
            get {
                return ResourceManager.GetString("FA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (U.S. West Coast).
        /// </summary>
        public static string FA6 {
            get {
                return ResourceManager.GetString("FA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (Juneau).
        /// </summary>
        public static string FA7 {
            get {
                return ResourceManager.GetString("FA7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (Anchorage).
        /// </summary>
        public static string FA8 {
            get {
                return ResourceManager.GetString("FA8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviation Area Forecast (Fairbanks).
        /// </summary>
        public static string FA9 {
            get {
                return ResourceManager.GetString("FA9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Danger Indices.
        /// </summary>
        public static string FDI {
            get {
                return ResourceManager.GetString("FDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Flood Watch.
        /// </summary>
        public static string FFA {
            get {
                return ResourceManager.GetString("FFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Flood Guidance.
        /// </summary>
        public static string FFG {
            get {
                return ResourceManager.GetString("FFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headwater Guidance.
        /// </summary>
        public static string FFH {
            get {
                return ResourceManager.GetString("FFH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Flood Statement.
        /// </summary>
        public static string FFS {
            get {
                return ResourceManager.GetString("FFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Flood Warning.
        /// </summary>
        public static string FFW {
            get {
                return ResourceManager.GetString("FFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Flood Summary.
        /// </summary>
        public static string FLN {
            get {
                return ResourceManager.GetString("FLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Statement.
        /// </summary>
        public static string FLS {
            get {
                return ResourceManager.GetString("FLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Warning.
        /// </summary>
        public static string FLW {
            get {
                return ResourceManager.GetString("FLW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Medium Range Guidance.
        /// </summary>
        public static string FMR {
            get {
                return ResourceManager.GetString("FMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Wind Fallout Forecast.
        /// </summary>
        public static string FOF {
            get {
                return ResourceManager.GetString("FOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA FOUS Freezing and Relative Humidity.
        /// </summary>
        public static string FOH {
            get {
                return ResourceManager.GetString("FOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Warning.
        /// </summary>
        public static string FRW {
            get {
                return ResourceManager.GetString("FRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban and Small Stream Flood Advisory (Obsolete).
        /// </summary>
        public static string FSS {
            get {
                return ResourceManager.GetString("FSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSR-88D Radar Status Notification.
        /// </summary>
        public static string FTM {
            get {
                return ResourceManager.GetString("FTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Weather Administrative Message.
        /// </summary>
        public static string FWA {
            get {
                return ResourceManager.GetString("FWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGM Mos Guidance.
        /// </summary>
        public static string FWC {
            get {
                return ResourceManager.GetString("FWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Weather Outlook Discussion.
        /// </summary>
        public static string FWD {
            get {
                return ResourceManager.GetString("FWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Fire Weather Outlook.
        /// </summary>
        public static string FWE {
            get {
                return ResourceManager.GetString("FWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine Fire WX Forecasts.
        /// </summary>
        public static string FWF {
            get {
                return ResourceManager.GetString("FWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Management Forecasts.
        /// </summary>
        public static string FWL {
            get {
                return ResourceManager.GetString("FWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Fire Weather Product.
        /// </summary>
        public static string FWM {
            get {
                return ResourceManager.GetString("FWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Weather Notification.
        /// </summary>
        public static string FWN {
            get {
                return ResourceManager.GetString("FWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Weather Observation.
        /// </summary>
        public static string FWO {
            get {
                return ResourceManager.GetString("FWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression Forecast.
        /// </summary>
        public static string FWS {
            get {
                return ResourceManager.GetString("FWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Level Data.
        /// </summary>
        public static string FZL {
            get {
                return ResourceManager.GetString("FZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Lakes Forecast.
        /// </summary>
        public static string GLF {
            get {
                return ResourceManager.GetString("GLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Lakes Storm Outlook.
        /// </summary>
        public static string GLO {
            get {
                return ResourceManager.GetString("GLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Lakes Storm Summary.
        /// </summary>
        public static string GLS {
            get {
                return ResourceManager.GetString("GLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Status Message.
        /// </summary>
        public static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrometeorlogical Coordination Message.
        /// </summary>
        public static string HCM {
            get {
                return ResourceManager.GetString("HCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurricane Local Statement.
        /// </summary>
        public static string HLS {
            get {
                return ResourceManager.GetString("HLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrometeorological Discussion.
        /// </summary>
        public static string HMD {
            get {
                return ResourceManager.GetString("HMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous Materials Warning.
        /// </summary>
        public static string HMW {
            get {
                return ResourceManager.GetString("HMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Weather Roundup.
        /// </summary>
        public static string HRR {
            get {
                return ResourceManager.GetString("HRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Seas Forecast.
        /// </summary>
        public static string HSF {
            get {
                return ResourceManager.GetString("HSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous Weather Outlook.
        /// </summary>
        public static string HWO {
            get {
                return ResourceManager.GetString("HWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall Reports.
        /// </summary>
        public static string HYD {
            get {
                return ResourceManager.GetString("HYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Hydrometerological Plain Language Product.
        /// </summary>
        public static string HYM {
            get {
                return ResourceManager.GetString("HYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Forecast.
        /// </summary>
        public static string ICE {
            get {
                return ResourceManager.GetString("ICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Observation.
        /// </summary>
        public static string IOB {
            get {
                return ResourceManager.GetString("IOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Alive Message.
        /// </summary>
        public static string KPA {
            get {
                return ResourceManager.GetString("KPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Area Emergency.
        /// </summary>
        public static string LAE {
            get {
                return ResourceManager.GetString("LAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Lakes Weather Observation.
        /// </summary>
        public static string LAW {
            get {
                return ResourceManager.GetString("LAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Cooperative Observation.
        /// </summary>
        public static string LCO {
            get {
                return ResourceManager.GetString("LCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law Enforcement Warning.
        /// </summary>
        public static string LEW {
            get {
                return ResourceManager.GetString("LEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Forecast.
        /// </summary>
        public static string LFP {
            get {
                return ResourceManager.GetString("LFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-Level Sounding.
        /// </summary>
        public static string LLS {
            get {
                return ResourceManager.GetString("LLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakeshore Warning or Statement.
        /// </summary>
        public static string LSH {
            get {
                return ResourceManager.GetString("LSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Storm Report.
        /// </summary>
        public static string LSR {
            get {
                return ResourceManager.GetString("LSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Data.
        /// </summary>
        public static string LTG {
            get {
                return ResourceManager.GetString("LTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFS Based MOS Guidance.
        /// </summary>
        public static string MAV {
            get {
                return ResourceManager.GetString("MAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA Based MOS Guidance.
        /// </summary>
        public static string MET {
            get {
                return ResourceManager.GetString("MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFX Extended Based MOS Guidance.
        /// </summary>
        public static string MEX {
            get {
                return ResourceManager.GetString("MEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Interpretation Message.
        /// </summary>
        public static string MIM {
            get {
                return ResourceManager.GetString("MIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Local Product.
        /// </summary>
        public static string MIS {
            get {
                return ResourceManager.GetString("MIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Message.
        /// </summary>
        public static string MON {
            get {
                return ResourceManager.GetString("MON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METAR Formatted Surface Weather Observation.
        /// </summary>
        public static string MTR {
            get {
                return ResourceManager.GetString("MTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Weather Statement.
        /// </summary>
        public static string MWS {
            get {
                return ResourceManager.GetString("MWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Weather Message.
        /// </summary>
        public static string MWW {
            get {
                return ResourceManager.GetString("MWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term Forecast.
        /// </summary>
        public static string NOW {
            get {
                return ResourceManager.GetString("NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Precipitation Message.
        /// </summary>
        public static string NPW {
            get {
                return ResourceManager.GetString("NPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearshore Marine Forecast / Surf Forecast.
        /// </summary>
        public static string NSH {
            get {
                return ResourceManager.GetString("NSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclear Power Plant Warning.
        /// </summary>
        public static string NUW {
            get {
                return ResourceManager.GetString("NUW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Aviation Products.
        /// </summary>
        public static string OAV {
            get {
                return ResourceManager.GetString("OAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offshore Forecast.
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Marine Products.
        /// </summary>
        public static string OMR {
            get {
                return ResourceManager.GetString("OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Public Products.
        /// </summary>
        public static string OPU {
            get {
                return ResourceManager.GetString("OPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Surface Observations.
        /// </summary>
        public static string OSO {
            get {
                return ResourceManager.GetString("OSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed Burn Forecast.
        /// </summary>
        public static string PBF {
            get {
                return ResourceManager.GetString("PBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Forecast Matrices.
        /// </summary>
        public static string PFM {
            get {
                return ResourceManager.GetString("PFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Fire Weather Forecast Matrices.
        /// </summary>
        public static string PFW {
            get {
                return ResourceManager.GetString("PFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Language Ship Report.
        /// </summary>
        public static string PLS {
            get {
                return ResourceManager.GetString("PLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prognostic Meteorological Discussion.
        /// </summary>
        public static string PMD {
            get {
                return ResourceManager.GetString("PMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Information Statement.
        /// </summary>
        public static string PNS {
            get {
                return ResourceManager.GetString("PNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Extended Forecast Discussion.
        /// </summary>
        public static string PRE {
            get {
                return ResourceManager.GetString("PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Storm Hurricane Report.
        /// </summary>
        public static string PSH {
            get {
                return ResourceManager.GetString("PSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Severe Weather Alert.
        /// </summary>
        public static string PWO {
            get {
                return ResourceManager.GetString("PWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilistic Tropical Cyclone Wind Speed.
        /// </summary>
        public static string PWS {
            get {
                return ResourceManager.GetString("PWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantitative Precipitation Forecast.
        /// </summary>
        public static string QPF {
            get {
                return ResourceManager.GetString("QPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantitative Precipitation Statement.
        /// </summary>
        public static string QPS {
            get {
                return ResourceManager.GetString("QPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSR-88D Radar Coded Message.
        /// </summary>
        public static string RCM {
            get {
                return ResourceManager.GetString("RCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Digital Forecast.
        /// </summary>
        public static string RDF {
            get {
                return ResourceManager.GetString("RDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Digital Guidance.
        /// </summary>
        public static string RDG {
            get {
                return ResourceManager.GetString("RDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreational Report.
        /// </summary>
        public static string REC {
            get {
                return ResourceManager.GetString("REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Event Report.
        /// </summary>
        public static string RER {
            get {
                return ResourceManager.GetString("RER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangeland Fire Danger Forecast.
        /// </summary>
        public static string RFD {
            get {
                return ResourceManager.GetString("RFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Forecast.
        /// </summary>
        public static string RFR {
            get {
                return ResourceManager.GetString("RFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Flag Warning.
        /// </summary>
        public static string RFW {
            get {
                return ResourceManager.GetString("RFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiological Hazard Warning.
        /// </summary>
        public static string RHW {
            get {
                return ResourceManager.GetString("RHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrology Meteorology Data Report Part 1.
        /// </summary>
        public static string RR1 {
            get {
                return ResourceManager.GetString("RR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrology Meteorology Data Report Part 2.
        /// </summary>
        public static string RR2 {
            get {
                return ResourceManager.GetString("RR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Hydrologic Observation STA Report.
        /// </summary>
        public static string RRA {
            get {
                return ResourceManager.GetString("RRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCS Manual Snow Course Data.
        /// </summary>
        public static string RRC {
            get {
                return ResourceManager.GetString("RRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Hydrologic Data.
        /// </summary>
        public static string RRM {
            get {
                return ResourceManager.GetString("RRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Automated Hydromet Data Report.
        /// </summary>
        public static string RRS {
            get {
                return ResourceManager.GetString("RRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max/Min Temperature and Precipitation Table.
        /// </summary>
        public static string RTP {
            get {
                return ResourceManager.GetString("RTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Summary.
        /// </summary>
        public static string RVA {
            get {
                return ResourceManager.GetString("RVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily River Forecast.
        /// </summary>
        public static string RVD {
            get {
                return ResourceManager.GetString("RVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Forecast.
        /// </summary>
        public static string RVF {
            get {
                return ResourceManager.GetString("RVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Ice Statement.
        /// </summary>
        public static string RVI {
            get {
                return ResourceManager.GetString("RVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous River Product.
        /// </summary>
        public static string RVM {
            get {
                return ResourceManager.GetString("RVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Recreation Statement.
        /// </summary>
        public static string RVR {
            get {
                return ResourceManager.GetString("RVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Statement.
        /// </summary>
        public static string RVS {
            get {
                return ResourceManager.GetString("RVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Roundup.
        /// </summary>
        public static string RWR {
            get {
                return ResourceManager.GetString("RWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Summary.
        /// </summary>
        public static string RWS {
            get {
                return ResourceManager.GetString("RWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Zone Forecast.
        /// </summary>
        public static string RZF {
            get {
                return ResourceManager.GetString("RZF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow Avalanche Bulletin.
        /// </summary>
        public static string SAB {
            get {
                return ResourceManager.GetString("SAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speci Agri WX FCST/Advisory/Flying Farmer FCST Outlook.
        /// </summary>
        public static string SAF {
            get {
                return ResourceManager.GetString("SAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prelim Notice of Watch &amp; Cancellation MSG.
        /// </summary>
        public static string SAW {
            get {
                return ResourceManager.GetString("SAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm Summary.
        /// </summary>
        public static string SCC {
            get {
                return ResourceManager.GetString("SCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary Climatological Data (ASOS).
        /// </summary>
        public static string SCD {
            get {
                return ResourceManager.GetString("SCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Cities Summary.
        /// </summary>
        public static string SCS {
            get {
                return ResourceManager.GetString("SCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Dispersion Statement.
        /// </summary>
        public static string SDS {
            get {
                return ResourceManager.GetString("SDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Local Storm Watch and Watch Cancellation.
        /// </summary>
        public static string SEL {
            get {
                return ResourceManager.GetString("SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPC Watch Point Information Message.
        /// </summary>
        public static string SEV {
            get {
                return ResourceManager.GetString("SEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Forecast Discussion.
        /// </summary>
        public static string SFD {
            get {
                return ResourceManager.GetString("SFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Forecast.
        /// </summary>
        public static string SFP {
            get {
                return ResourceManager.GetString("SFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabular State Forecast.
        /// </summary>
        public static string SFT {
            get {
                return ResourceManager.GetString("SFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Ship Report at Synoptic Time.
        /// </summary>
        public static string SHP {
            get {
                return ResourceManager.GetString("SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Interpretation Message.
        /// </summary>
        public static string SIM {
            get {
                return ResourceManager.GetString("SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Local Storm Watch and Areal Outline.
        /// </summary>
        public static string SLS {
            get {
                return ResourceManager.GetString("SLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Management Weather Forecast.
        /// </summary>
        public static string SMF {
            get {
                return ResourceManager.GetString("SMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Marine Warning.
        /// </summary>
        public static string SMW {
            get {
                return ResourceManager.GetString("SMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Precipitation Estimates.
        /// </summary>
        public static string SPE {
            get {
                return ResourceManager.GetString("SPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm Strike Probability Bulletin.
        /// </summary>
        public static string SPF {
            get {
                return ResourceManager.GetString("SPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Weather Statement.
        /// </summary>
        public static string SPS {
            get {
                return ResourceManager.GetString("SPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter in Place Warning.
        /// </summary>
        public static string SPW {
            get {
                return ResourceManager.GetString("SPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surf Forecast.
        /// </summary>
        public static string SRF {
            get {
                return ResourceManager.GetString("SRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPC Tornado and Severe Thunderstorm Reports.
        /// </summary>
        public static string STA {
            get {
                return ResourceManager.GetString("STA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Tropical Disturbance Summary.
        /// </summary>
        public static string STD {
            get {
                return ResourceManager.GetString("STD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Condition Reports.
        /// </summary>
        public static string STO {
            get {
                return ResourceManager.GetString("STO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Max/Min Temperature and Precipitation Table.
        /// </summary>
        public static string STP {
            get {
                return ResourceManager.GetString("STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Weather Message Summary.
        /// </summary>
        public static string SUM {
            get {
                return ResourceManager.GetString("SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Thunderstorm Warning.
        /// </summary>
        public static string SVR {
            get {
                return ResourceManager.GetString("SVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Weather Statement.
        /// </summary>
        public static string SVS {
            get {
                return ResourceManager.GetString("SVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Storm Outlook Narrative.
        /// </summary>
        public static string SWO {
            get {
                return ResourceManager.GetString("SWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Weather Roundup.
        /// </summary>
        public static string SWR {
            get {
                return ResourceManager.GetString("SWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Weather Summary.
        /// </summary>
        public static string SWS {
            get {
                return ResourceManager.GetString("SWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Synopsis.
        /// </summary>
        public static string SYN {
            get {
                return ResourceManager.GetString("SYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Aerodrome Forecast.
        /// </summary>
        public static string TAF {
            get {
                return ResourceManager.GetString("TAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travelers Forecast Table.
        /// </summary>
        public static string TAV {
            get {
                return ResourceManager.GetString("TAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Cyclone Advisory.
        /// </summary>
        public static string TCA {
            get {
                return ResourceManager.GetString("TCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Cyclone Discussion.
        /// </summary>
        public static string TCD {
            get {
                return ResourceManager.GetString("TCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Cyclone Position Estimate.
        /// </summary>
        public static string TCE {
            get {
                return ResourceManager.GetString("TCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine/Aviation Tropical Cyclone Advisory.
        /// </summary>
        public static string TCM {
            get {
                return ResourceManager.GetString("TCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Tropical Cyclone Advisory.
        /// </summary>
        public static string TCP {
            get {
                return ResourceManager.GetString("TCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Tropical Cyclone Summary.
        /// </summary>
        public static string TCS {
            get {
                return ResourceManager.GetString("TCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Cyclone Update.
        /// </summary>
        public static string TCU {
            get {
                return ResourceManager.GetString("TCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Cyclone Watch/Warning.
        /// </summary>
        public static string TCV {
            get {
                return ResourceManager.GetString("TCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsunami Information Bulletin.
        /// </summary>
        public static string TIB {
            get {
                return ResourceManager.GetString("TIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Report.
        /// </summary>
        public static string TID {
            get {
                return ResourceManager.GetString("TID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsunami Tide/Seismic Message Acknowledgment.
        /// </summary>
        public static string TMA {
            get {
                return ResourceManager.GetString("TMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 911 Telephone Outage Emergency.
        /// </summary>
        public static string TOE {
            get {
                return ResourceManager.GetString("TOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado Warning.
        /// </summary>
        public static string TOR {
            get {
                return ResourceManager.GetString("TOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Precipitation Table.
        /// </summary>
        public static string TPT {
            get {
                return ResourceManager.GetString("TPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsunami Tide/Seismic Message.
        /// </summary>
        public static string TSM {
            get {
                return ResourceManager.GetString("TSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Message.
        /// </summary>
        public static string TST {
            get {
                return ResourceManager.GetString("TST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsunami Watch/Warning.
        /// </summary>
        public static string TSU {
            get {
                return ResourceManager.GetString("TSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travelers Forecast.
        /// </summary>
        public static string TVL {
            get {
                return ResourceManager.GetString("TVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Weather Discussion.
        /// </summary>
        public static string TWD {
            get {
                return ResourceManager.GetString("TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Weather Outlook and Summary.
        /// </summary>
        public static string TWO {
            get {
                return ResourceManager.GetString("TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Weather Summary.
        /// </summary>
        public static string TWS {
            get {
                return ResourceManager.GetString("TWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultraviolet Index.
        /// </summary>
        public static string UVI {
            get {
                return ResourceManager.GetString("UVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanic Activity Advisory.
        /// </summary>
        public static string VAA {
            get {
                return ResourceManager.GetString("VAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcano Warning.
        /// </summary>
        public static string VOW {
            get {
                return ResourceManager.GetString("VOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Environment Warning.
        /// </summary>
        public static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Weather Message Watch.
        /// </summary>
        public static string WAT {
            get {
                return ResourceManager.GetString("WAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch County Notification.
        /// </summary>
        public static string WCN {
            get {
                return ResourceManager.GetString("WCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Weather and Crop Report.
        /// </summary>
        public static string WCR {
            get {
                return ResourceManager.GetString("WCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Data for Agriculture.
        /// </summary>
        public static string WDA {
            get {
                return ResourceManager.GetString("WDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27-day Space Weather Forecast.
        /// </summary>
        public static string WEK {
            get {
                return ResourceManager.GetString("WEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Outline Update.
        /// </summary>
        public static string WOU {
            get {
                return ResourceManager.GetString("WOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Work File.
        /// </summary>
        public static string WRK {
            get {
                return ResourceManager.GetString("WRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Weather Message.
        /// </summary>
        public static string WSW {
            get {
                return ResourceManager.GetString("WSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Verification Message.
        /// </summary>
        public static string WVM {
            get {
                return ResourceManager.GetString("WVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Status Report.
        /// </summary>
        public static string WWA {
            get {
                return ResourceManager.GetString("WWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Thunderstorm Watch Probabilities.
        /// </summary>
        public static string WWP {
            get {
                return ResourceManager.GetString("WWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Forecast Product.
        /// </summary>
        public static string ZFP {
            get {
                return ResourceManager.GetString("ZFP", resourceCulture);
            }
        }
    }
}
