//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emwin.Core.References {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VtecPhenomenon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VtecPhenomenon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emwin.Core.References.VtecPhenomenon", typeof(VtecPhenomenon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashfall.
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Stagnation.
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalanche.
        /// </summary>
        public static string AV {
            get {
                return ResourceManager.GetString("AV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Hazard.
        /// </summary>
        public static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowing Snow.
        /// </summary>
        public static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisk Wind.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        public static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastal Flood.
        /// </summary>
        public static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust Storm.
        /// </summary>
        public static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowing Dust.
        /// </summary>
        public static string DU {
            get {
                return ResourceManager.GetString("DU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Cold.
        /// </summary>
        public static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive Heat.
        /// </summary>
        public static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Wind.
        /// </summary>
        public static string EW {
            get {
                return ResourceManager.GetString("EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areal Flood.
        /// </summary>
        public static string FA {
            get {
                return ResourceManager.GetString("FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Flood.
        /// </summary>
        public static string FF {
            get {
                return ResourceManager.GetString("FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dense Fog.
        /// </summary>
        public static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood.
        /// </summary>
        public static string FL {
            get {
                return ResourceManager.GetString("FL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Weather.
        /// </summary>
        public static string FW {
            get {
                return ResourceManager.GetString("FW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        public static string FZ {
            get {
                return ResourceManager.GetString("FZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gale.
        /// </summary>
        public static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurricane Force Wind.
        /// </summary>
        public static string HF {
            get {
                return ResourceManager.GetString("HF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inland Hurricane Wind.
        /// </summary>
        public static string HI {
            get {
                return ResourceManager.GetString("HI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Snow.
        /// </summary>
        public static string HS {
            get {
                return ResourceManager.GetString("HS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurricane.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Wind.
        /// </summary>
        public static string HW {
            get {
                return ResourceManager.GetString("HW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrologic.
        /// </summary>
        public static string HY {
            get {
                return ResourceManager.GetString("HY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Freeze.
        /// </summary>
        public static string HZ {
            get {
                return ResourceManager.GetString("HZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleet.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Storm.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake Effect Snow and Blowing Snow.
        /// </summary>
        public static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake Effect Snow.
        /// </summary>
        public static string LE {
            get {
                return ResourceManager.GetString("LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Water.
        /// </summary>
        public static string LO {
            get {
                return ResourceManager.GetString("LO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakeshore Flood.
        /// </summary>
        public static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake Wind.
        /// </summary>
        public static string LW {
            get {
                return ResourceManager.GetString("LW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine.
        /// </summary>
        public static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Dense Fog.
        /// </summary>
        public static string MF {
            get {
                return ResourceManager.GetString("MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Ashfall.
        /// </summary>
        public static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Dense Smoke.
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Craft for Rough Bar.
        /// </summary>
        public static string RB {
            get {
                return ResourceManager.GetString("RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rip Currents.
        /// </summary>
        public static string RP {
            get {
                return ResourceManager.GetString("RP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow And Blowing Snow.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Craft.
        /// </summary>
        public static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous Seas.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Craft for Winds.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        public static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm.
        /// </summary>
        public static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Surf.
        /// </summary>
        public static string SU {
            get {
                return ResourceManager.GetString("SU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Thunderstorm.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Craft for Hazardous Seas.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inland Tropical Storm Wind.
        /// </summary>
        public static string TI {
            get {
                return ResourceManager.GetString("TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado.
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Storm.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsunami.
        /// </summary>
        public static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typhoon.
        /// </summary>
        public static string TY {
            get {
                return ResourceManager.GetString("TY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Spray.
        /// </summary>
        public static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Chill.
        /// </summary>
        public static string WC {
            get {
                return ResourceManager.GetString("WC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string WI {
            get {
                return ResourceManager.GetString("WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Storm.
        /// </summary>
        public static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Weather.
        /// </summary>
        public static string WW {
            get {
                return ResourceManager.GetString("WW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Fog.
        /// </summary>
        public static string ZF {
            get {
                return ResourceManager.GetString("ZF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Rain.
        /// </summary>
        public static string ZR {
            get {
                return ResourceManager.GetString("ZR", resourceCulture);
            }
        }
    }
}
