//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emwin.Core.References {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VtecAction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VtecAction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emwin.Core.References.VtecAction", typeof(VtecAction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CAN {
            get {
                return ResourceManager.GetString("CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continued.
        /// </summary>
        public static string CON {
            get {
                return ResourceManager.GetString("CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected.
        /// </summary>
        public static string COR {
            get {
                return ResourceManager.GetString("COR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed in Area.
        /// </summary>
        public static string EXA {
            get {
                return ResourceManager.GetString("EXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed in Time and Area.
        /// </summary>
        public static string EXB {
            get {
                return ResourceManager.GetString("EXB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string EXP {
            get {
                return ResourceManager.GetString("EXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed in Time.
        /// </summary>
        public static string EXT {
            get {
                return ResourceManager.GetString("EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine.
        /// </summary>
        public static string ROU {
            get {
                return ResourceManager.GetString("ROU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgraded.
        /// </summary>
        public static string UPG {
            get {
                return ResourceManager.GetString("UPG", resourceCulture);
            }
        }
    }
}
